### ISSUE TITLE
Potential issue related to default temp in vvb sensor

### ISSUE THREAD

**Issue by yNaess** [erlendsellie/priceanalyzer#11] opened 2022-11-10 13:05 UTC
A combination of these two occurrences might show a bug:
- "Settings for custom degrees for Hot Water sensor" in the Priceanalyzer integration configuration. My line starts with {"default_temp": 0, ....}
- Tomorrow (will be Nov 11) the power price is low and stable, which triggers the reasons as displayed in Dev tool -> states: raw_tomorrow for vvb sensor: "Small price difference or below threshold for settings"

The "temp" becomes 75 in raw_tomorrow, even though custom settings is set as follows: "default_temp": 0

A way to overcome the issue (bug?), is to replace 75 with 0 (in my case) in line 78 in sensor.py

**Comment by erlendsellie** [comment] 2022-11-10 19:06
Thanks for the issue!

This is indeed caused by the line 78 in sensor.py: `        temp = self.getConfigKey(TEMP_DEFAULT) or 75`
The line sets the default temp, with a fallback to 75, if the config set for default temp is 'falsy'.
That means if the value set is an empty string, not set at all, or in this case, the number 0.

I newer thought anybody would set the default temperature of the hot water tank to 0 degrees, but here we are. I'll try to come up with a better solution, which accepts 0 as a temperature setting.

Remember though, that this is the temperature that will be set, if the NordPool API for some reason is down, my code fails, or anything else happens. This is the fallback-temperature, as well as the ""Small price difference or below threshold for settings"-temperature. 
So setting it to 0, wil effecitively turn off your hot water heater when the price is low, the price curve for the day is flat, or if there is an issue with the NordPool-API.

**Comment by yNaess** [comment] 2022-11-10 19:33
I understand, and that makes perfect sense. I am using the vvb sensor a bit differently than most, so I am happy to just replace 75 with 0 in my setup.
I am actually using the vvb sensor for regulating thermostats (the task of the priceanalyzer sensor, really), since i found it to give good control/visualization of when to increase/decrease.  Found this setup superior to other similar integrations, and now use this config on all thermostats:
{"default_temp": 0, "five_most_expensive": -1,"is_falling": -1, "five_cheapest": 1, "ten_cheapest": 1, "low_price": 0, "not_cheap_not_expensive": 0, "min_price_for_day": 1}
Love your integration! Keep up the good work :)

**Comment by erlendsellie** [comment] 2022-11-10 22:32
Ahh, i see! I'll still try to fix the issue, so that you won't have to fix the line whenever a new version is released.
That's not a dumb idea. The VVB-sensor is the newest one, and therefore has the most functionality, like this configuration.
I think i'll add some kind of configuration like this to PriceAnalyzer as well, but probably based on some other parameters.
'Ten cheapest', 'Five most expensive' and so on may not be the best options for thermostats, as the air in rooms don't magazines the heat the same way a hot water tank does. 
When you heat up the hot water tank for the ten cheapest hours in a day, it'll probably be enough for the whole day, but that does not translate well to thermostat's, depending on thermodynamic variables like heat source, insulation, draft, and so on.  The extra energy used to heat up the house in the five cheapest hours at night, right after bedtime for example, are most probably just gone when you get out of bed hours later.
That's why the PriceAnalyzer sensor works a bit different, by boosting when 'the price is about to get more expensive' and saving when 'the price is about to the cheaper'. 

But if this really helps for the electricy bill or not is mostly guesstimation. 

The Priceanalyzer sensor also has an Apex Chart that will visualize how it plans to increase/decrease, and use can also use the priceanalyzer sensor in the Apex Charts example for the VVB Sensor.

But i'm not telling you how to use it, just explaining why they are different sensors and what sets them apart. It's fun to see it used this way as well! :-)

Thanks for the feedback, really appreciate it!

**Comment by erlendsellie** [comment] 2022-11-13 20:53
Should be fixed in 1.1 :-)

**Closed by erlendsellie** 2022-11-13 20:53 UTC
